### ISSUE TITLE
New, preferred DOI resolver doubles URL variants

### ISSUE THREAD

**Issue by katrinleinweber** [rajarshi/genpubs#1]
Hello :-)

It seems to me that https://github.com/rajarshi/genpubs/blob/6b75ecd5d642ad1b61fd4fb5801b685702311708/genpubs.py#L123-L134

would not catch/clean the [new `https://doi.org/`](https://www.doi.org/doi_handbook/3_Resolution.html#3.8)-URLs, would it?

Maybe that code could be shortened, but turned into a reg-ex as in https://github.com/getcontacts/atlas/commit/cd8481ec32f92c11ca87661a9300330b361e9ebf ? Would that be useful here?

**Comment by rajarshi** [comment]
Thanks for the suggestion - fixed in master

**Comment by katrinleinweber** [comment]
You're welcome :-)
